FPGA_File_Name:           SILVERSTONE_FPGA_primary_V0001_0005.bin
BIOS_File_Name:           Silverstone_BIOS_2.0.0.BIN
CPLD_File_Name:           Silverstone_V05_FAN_V03_BASE_V05_COME_V07_SW1_V00_SW2_V00.vme
BMC_File_Name:            R4009-JF002-01_Silverstone_B2F_BMCV2.01.ima
SDK_Version:              sdk-6.5.16 built 20190801
PCIE_FW_Name:             pcieg3fw.bin
Fan_PN:                   0210D9
Fan_Rev:                  "02"
BMC_Product:              Z9332F-ON-BMC
FPGA_Version:             "10005"
BIOS_Version:             "2.0.0"
BMC_Version:              "02 01"

Firmware_Version:
  CPLD_Base_Board:        0a
  CPLD_Fan_Board:         "03"
  CPLD_Fan_Board2:        "0x3"
  CPLD_ComE:              "11"
  CPLD_Switch1:           "01"
  CPLD_Switch2:           "01"
  BMC1_Version:           "1.01"
  BMC2_Version:           "01 01"
  Bios_Version:           "2.0.7"
  FPGA_Version:           "00010006"
  ONL_Version:            ONL-1.3
  Diag_Version:           "1.0.4"
  ONIE_Version:           "0.0.3"
  FPGA_Code_Version:      "0.6"
  SSD_FW_Version:         L20B12
  PCIE1_FW_Version:       "2.5"
  PCIE2_FW_Version:       D102_08

TLV_Version:
  Product_Name:           Silverstone B2F
  Device_Version:         "1"
  Platform_Name:          Broadwell-DE
  ONIE_Version:           "0.0.5"
  MAC_Addresses:          "262"
  Manufacturer:           Celestica
  Country_Code:           THA
  Diag_Version:           "2.0.1"
  New_Device_Version:     "01"
  Service_tag:            LB
  Vendor_B2F:             0x2F 0xD4 0xBF
  Vendor_F2B:             0x2F 0xD4 0xFB

SMBios_Version:
  System_Manufacturer:    Celestica
  System_Product:         Silverstone B2F
  Board_Manufacturer:     Celestica
  Chassis_Location:       Silverstone_B2F_CPU_CARD
  Chassis_Manufacturer:   Celestica
  Chassis_Version:        "02"
  Chassis_Asset_Tag:      R4009-F0001-01